import {
  formatPrice,
  calculateCartTotal,
  calculateCartSavings,
  getItemUnitPrice,
  getProductTotalQtyInCart,
  generateOrderNumber,
} from '../utils';
import type { Product } from '@/types';

const miniRobe: Product = {
  id: 'mini-robe-brode-anglais-100-coton',
  name: 'Mini robe brodé anglais 100% coton',
  price: 13000,
  category: 'robes',
  gender: 'femme',
  description: '',
  material: '',
  care: '',
  sizes: ['S'],
  colors: [{ name: 'Blanc Broderie', hex: '#FAF9F6' }],
  images: ['/image.jpg'],
};

const anotherProduct: Product = {
  id: 'robe-soleil',
  name: 'Robe soleil',
  price: 25000,
  category: 'robes',
  gender: 'femme',
  description: '',
  material: '',
  care: '',
  sizes: ['M'],
  colors: [{ name: 'Rouge', hex: '#FF0000' }],
  images: ['/image2.jpg'],
};

describe('formatPrice', () => {
  it('formats an amount in FCFA with French number formatting', () => {
    expect(formatPrice(13000).replace(/\s/g, ' ')).toBe('13 000 FCFA');
    expect(formatPrice(0).replace(/\s/g, ' ')).toBe('0 FCFA');
  });
});

describe('getItemUnitPrice', () => {
  it('returns the product price by default', () => {
    expect(getItemUnitPrice(anotherProduct, 1)).toBe(25000);
  });

  it('applies the bulk discount on the mini robe from 6 units', () => {
    expect(getItemUnitPrice(miniRobe, 5)).toBe(13000);
    expect(getItemUnitPrice(miniRobe, 6)).toBe(11000);
  });
});

describe('getProductTotalQtyInCart', () => {
  it('sums quantities across all cart lines of the same product model', () => {
    const items = [
      { product: { id: miniRobe.id }, quantity: 2 },
      { product: { id: miniRobe.id }, quantity: 4 },
      { product: { id: anotherProduct.id }, quantity: 1 },
    ];
    expect(getProductTotalQtyInCart(items, miniRobe.id)).toBe(6);
    expect(getProductTotalQtyInCart(items, anotherProduct.id)).toBe(1);
  });
});

describe('calculateCartTotal', () => {
  it('computes a simple subtotal without discount', () => {
    const items = [
      {
        product: { id: 'a', price: 10000 },
        quantity: 2,
      },
    ];
    expect(calculateCartTotal(items)).toBe(20000);
  });

  it('applies the volume discount across sizes/colors of the same model', () => {
    const items = [
      { product: { id: miniRobe.id, price: 13000 }, quantity: 3 },
      { product: { id: miniRobe.id, price: 13000 }, quantity: 3 },
    ];
    expect(calculateCartTotal(items)).toBe(6 * 11000);
  });

  it('mixes discounted and regular products correctly', () => {
    const items = [
      { product: { id: miniRobe.id, price: 13000 }, quantity: 6 },
      { product: { id: anotherProduct.id, price: 25000 }, quantity: 1 },
    ];
    expect(calculateCartTotal(items)).toBe(6 * 11000 + 25000);
  });
});

describe('calculateCartSavings', () => {
  it('returns the savings generated by the volume discount', () => {
    const items = [
      { product: { id: miniRobe.id, price: 13000 }, quantity: 6 },
    ];
    expect(calculateCartSavings(items)).toBe(6 * (13000 - 11000));
  });

  it('returns 0 when there is no discount', () => {
    const items = [{ product: { id: anotherProduct.id, price: 25000 }, quantity: 1 }];
    expect(calculateCartSavings(items)).toBe(0);
  });
});

describe('generateOrderNumber', () => {
  it('returns an order number with the current year and 5 digits', () => {
    const orderNumber = generateOrderNumber();
    expect(orderNumber).toMatch(/^CMD-\d{4}-\d{5}$/);
    expect(orderNumber).toContain(String(new Date().getFullYear()));
  });
});